### ISSUE TITLE
Parsing of XML namespace declarations in XML input is incorrect

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#124]
Perhaps RNeXML has a built-in expectation for the abbreviation of the NeXML namespace? The following lines result in an error, complaining about the `ns` namespace:

```xml
<nexml xmlns="http://www.nexml.org/2009" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" version="0.9" xsi:schemaLocation="http://www.nexml.org/2009 http://www.nexml.org/2009/nexml.xsd http://www.bioontologies.org/obd/schema/pheno http://purl.org/phenoscape/phenoxml.xsd">
  <meta xmlns:ns="http://www.nexml.org/2009" xmlns:ter="http://purl.org/dc/terms/" xsi:type="ns:LiteralMeta" property="ter:creator"/>
```

This shouldn't result in an error. If one changes `ns:LiteralMeta` to `nex:LiteralMeta` (with `nex` not defined anywhere!), the error goes away. So this seems backwards to me - what shouldn't give an error does, and what should give an error doesn't.

What prompts this is that the Phenoscape API (cc @balhoff) apparently returns NeXML with the NeXML namespace defined (by a `xmlns:ns="http://www.nexml.org/2009"` attribute) from scratch for every single element for which it is needed, rather than once at the root element, and it always uses `ns` (which is legitimate, even if not pretty).

I have posted this over on the Phenoscape API too (phenoscape/phenoscape-kb-services#12) to declare this less verbose and using the standard prefix, but RNeXML should be able to read legitimately formatted NeXML.

For reference, [here is an original file](https://github.com/xu-hong/rphenoscape/blob/master/inst/examples/test_original.xml) as returned by the Phenoscape API, and here is an [edited file with the change throughout as per above](https://github.com/xu-hong/rphenoscape/blob/master/inst/examples/test.xml). The former raises an error with `nexml_read()`, the latter doesn't (but arguably should).

**Comment by cboettig** [comment]
Yes, is due to issue #51.

I believe this is essentially because NeXML namespaces attribute values, which XML treats as strings.  @hlapp's solution in #51 looks reasonable but has not yet been implemented.

**Comment by balhoff** [comment]
@hlapp in the next few weeks I will try to look into how to remove the redundant namespace declarations. I recall that it resulted from my workaround for the fact that the XML library I was using didn't automatically handle namespaces for attribute values.

**Comment by hlapp** [comment]
As an addition piece of information, here is the error that results from `nexml_read()` on the output returned by the Phenoscape API:

```
 Error in fromNeXML(new(type[1]), from) : 
  error in evaluating the argument 'obj' in selecting a method for function 'fromNeXML': Error in getClass(Class, where = topenv(parent.frame())) : 
  “ns:LiteralMeta” is not a defined class 
```

**Comment by balhoff** [comment]
I was wrong that it was a workaround I did. I use the XMLbeans API to write the documents. It looks like it always redundantly declares a namespace for writing QName attribute values. I know how to specify namespace prefixes for the whole document, but haven't yet found a way to specify which prefixes I want for these QName values.
