### ISSUE TITLE
Update package on CRAN

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#142]
It looks like the version currently up on CRAN doesn't include the more recent changes, which, for example, results in some warnings [when integration testing rphenoscape](https://travis-ci.org/xu-hong/rphenoscape). Although there seem to be ways now [to specify dependencies on packages that are on Github instead of CRAN](http://stackoverflow.com/questions/30493388/create-an-r-package-that-depends-on-another-r-package-located-on-github), shouldn't the RNeXML release on CRAN  just be updated?

**Comment by cboettig** [comment]
Definitely!  CRAN is very picky about these things though.  CRAN will refuse to accept updates it does not request if they come too frequently (except in the first month or so for a new package), even if those updates contain major bug fixes.  I think the usual interval is no more than one update every 2 months, but this is enforced somewhat variably and can be hard to predict.  I think it's been just about 2 months now, so we can go ahead and try. fingers crossed...

**Comment by cboettig** [comment]
Whoops, forgot to close this.  New version is on CRAN (as of 2015-12-31)
