### ISSUE TITLE
example with cite() function call fails

### ISSUE THREAD

**Issue by sckott** [ropensci/RNeXML#144]
in the `add_basic_meta` function examples

```r
library(knitcitations)
exml <- add_basic_meta(citation=cite("10.2307/2408428"))
#> Error in unlist(bib$key) : argument "bib" is missing, with no default
```

there is a `utils::cite`, but there's no function `cite` in this pkg, or in `knitcitations`, though `knitcitations` does have `citep` and `citet`, was one of those intended?

**Comment by cboettig** [comment]
looks like it should be `bib_metadata` instead of `cite`.  whoops.  (I think I was trying to avoid the collision with `utils` in the more recent `knitcitations` and changed the api...)
