### ISSUE TITLE
server.carlboettiger.info fails to resolve

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#149]
The `README` for the `manuscripts/` directory includes a badge from http://server.carlboettiger.info:88/github.com/ropensci/RNeXML, but the server name fails to resolve through DNS.

Is that badge good for something? If yes, is the server now under a different address?

**Comment by cboettig** [comment]
thanks, right, that server is no longer around and that badge should just be deprecated now, since the manuscript is now built on circleci instead (for which we already have a badge).

**Comment by cboettig** [comment]
Badge removed
