### ISSUE TITLE
suggest taxize

### ISSUE THREAD

**Issue by lawremi** [ropensci/RNeXML#166]
The taxize functionality seems somewhat extraneous to parsing the XML files. Would it make sense to move taxize to Suggests? Would eliminate a tree of dependencies.

**Comment by cboettig** [comment]
Good point.  It is used in the *creation* of NeXML to encourage users to include taxonomic IDs for all OTUs. 

The jury has conflicted opinions about using `Suggests` for things that functions in the package actually depend upon, even if they are bonus features (more accepted use is for things that are purely "development" dependencies, used for running tests or building vignettes or other documentation), but clearly we're already using this hack in other cases to slim the dependency weight a tiny bit.  

So I think you have a pretty compelling case, will try and get to it soon....

**Comment by cboettig** [comment]
@lawremi  Done, thanks for the suggestion!
