### ISSUE TITLE
are these test files still needed?

### ISSUE THREAD

**Issue by maelle** [ropensci/RNeXML#168]
https://github.com/ropensci/RNeXML_testfiles or should the repo be archived/deleted?

**Comment by hlapp** [comment]
I don't know for sure - looks like a candidate for deletion to me. @sckott and @cboettig ?

**Comment by sckott** [comment]
probably delete unless @cboettig can think of a reason to keep

**Comment by cboettig** [comment]
yup, delete

**Comment by maelle** [comment]
Ok done thanks a lot!
