### ISSUE TITLE
get_characters() fails with an error in dplyr::bind_rows()

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#171]
The [following line](https://github.com/ropensci/RNeXML/blob/4341d2465a4bbaf1693c5bc23209440a44a2c807/R/get_characters.R#L59) in `get_characters.R` fails with `Column `symbol` can't be converted from integer to character`:

```R
states <- dplyr::bind_rows(states, polymorph)
Error in bind_rows_(x, .id) : 
  Column `symbol` can't be converted from integer to character
```

This seems to happen only in R 3.5.+, not in R 3.3.x. I don't know whether this happens for all inputs with polymorphic characters or only some. I came across this from the Rphenoscape vignette, where it breaks rendering the vignette:

```R
install_github("xu-hong/rphenoscape")
library(rphenoscape)
nex <- pk_get_ontotrace_xml(taxon = c("Ictalurus", "Ameiurus"), entity = "fin spine")
m <- pk_get_ontotrace(nex)
```

The last instruction internally calls `get_characters()`:
```R
m <- get_characters(nex, rownames_as_col = TRUE,
                    otu_id = TRUE, otus_id = TRUE)
```

Which then results in the given error.

**Comment by cboettig** [comment]
Thanks!  And it looks like that line is an example of one not covered by current unit tests: https://codecov.io/gh/ropensci/RNeXML/src/master/R/get_characters.R#L59 

whoops!  

Should definitely be fixed.  Somewhat tangential, but actually hoping to have an RNeXML re-write in the near future based on the `nexld` approach which I think should make the code-base a lot simpler and more robust.  Meanwhile will try and patch this soon
