### ISSUE TITLE
.Rd files under version control

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#180]
I'm wondering whether the `.Rd` files should be indeed be under version control. Right now they are, although they are re-generated by Roxygen on every `R CMD build`, and they don't seem to necessarily be meant for human consumption (unlike, say, the `.md` files generated from `.Rmd`).

One reason I bring this up is that a number of these have inconsequential changes in them when I re-run `R CMD build` locally, such as the line breaks in a long argument list being placed differently. I.e., having these under version control will lead to a lot of "noise" introduced into `git status` and other commands.

**Comment by cboettig** [comment]
Yeah, I see your point, but committing them is standard practice.   Installing directly from GitHub using `install_github()` would break without them, as would the standard r-travis checks (though the latter could be hacked around).  

Usually they should only change when the Roxygen in the R files change.  The most recent Roxygen generator started enforcing line length I believe, so there will be a one-time extra noise when updating all the Roxygen docs.

**Comment by hlapp** [comment]
Fixed in ac2503a6020f41670f958f1d3c5a287d8970197a. Sorry that went straight to master by mistake.
