### ISSUE TITLE
Plans for update release to CRAN?

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#185]
The Rphenoscape package is dependent on the recent fixes resolving #171 and #172. Hence, I'm wondering when these could be reasonably expected to make it to CRAN? Are there other changes or fixes that should be in the same version upgrade? Should we create a milestone to track these?

Either way, Rphenoscape needs to depend on a version of RNeXML > 2.1.2.  Would it be OK to increment the version on the `master` branch, say to 2.1.3-0 or something similar if further changes would be coming before the 2.1.3. release on CRAN?

**Comment by cboettig** [comment]
@hlapp Sure, I think we could get a new release on CRAN in relatively short order.  None of the open issues seem mission critical to me, so I'd propose we prepare a release at the current state.  

Version wise, I can bump to 2.1.2.99 (R thinks that  `2.1.3-0` > `2.1.3`, try `compareVersion()`) for now, and make it `2.1.3` at release.  

Other steps:

- [ ] Can you contribute a line in `NEWS.md` for release notes about what is fixed from #171 / #172 ?
- [ ] Then I'll bump version, write the `cran-comments.md` letter, and run checks for release.

**Comment by hlapp** [comment]
BTW what's needed for version bump is only that the version it has satisfies being greater than or equal to `2.1.3` (if that's what I make minimally required for rphenoscape). As you say, `2.1.3.0` would accomplish that :smile:

In the meantime, I am using the `Remotes:` tag in DESCRIPTION to request that the RNeXML dependency be installed from Github. This accomplishes the desired outcome for those who don't have RNeXML installed already. Requiring `RNeXML >= 2.1.3` would have the nice benefit of flagging the need to upgrade for those who have it installed already.

It also turns out that in fact we're not release-ready here yet. The issue with polymorphic states is in fact not fixed yet. Issue and pull request will follow.

Yes I can add the `NEWS.md` line once we're there.

**Comment by hlapp** [comment]
> It also turns out that in fact we're not release-ready here yet. The issue with polymorphic states is in fact not fixed yet. Issue and pull request will follow.

Issue is #186. The solution I think will by definition need to (at least partially) address #175.

**Comment by cboettig** [comment]
Are we good to prepare a release now that #188 has resolved #186 and #175?  Think we just need some text for the `NEWs.md` release notes regarding the resolution of these issues.

**Comment by hlapp** [comment]
I looks like especially with #191 fixed in #192 we're good now. #193 is icing 😄 (or gravy, if you're that kind of guy 😁).

**Comment by cboettig** [comment]
Great! Can you give me a blurb for [NEWS.md](https://github.com/ropensci/RNeXML/blob/master/NEWS.md) release notes that summarizes the `get_character()` changes?  It can also link back to the relevant issue threads directly for details.  Then I can probably prepare a release to CRAN pretty soon

**Comment by cboettig** [comment]
@hlapp Are we ready to make a release to CRAN?  Just lemme know what should go into the  [NEWS.md](https://github.com/ropensci/RNeXML/blob/master/NEWS.md)

**Comment by hlapp** [comment]
> @hlapp Are we ready to make a release to CRAN? Just lemme know what should go into the NEWS.md

Yes, just tied up this week with teaching,

**Comment by hlapp** [comment]
I think we are done here, @cboettig ?
