### ISSUE TITLE
Failure to handle nested meta elements

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#196]
Reading the following file (which successfully validates with the NeXML validator) results in an error:
```R
nex = read.nexml("https://raw.githubusercontent.com/phenoscape/phenoscape-data/master/curation-files/teleost-incomplete-files/Dillman_Supermatrix_Files/Lucinda_Vari_2009.xml")
  Error in attrs[["href"]] : subscript out of bounds
```
I believe this is because it chokes on the following meta element:
```xml
<meta xsi:type="ResourceMeta" rel="dc:source">
  <meta xsi:type="LiteralMeta" property="dc:identifier">https://doi.org/10.1643/CI-08-076</meta>
  <meta xsi:type="LiteralMeta" property="dc:bibliographicCitation">Lucinda, P. H. F. and R. P. Vari. 2009. New Steindachnerina species (Teleostei: Characiformes: Curimatidae) from the Rio Tocantins basin. Copeia, 2009(1):142-147</meta>
  <meta xsi:type="LiteralMeta" property="dc:title">Lucinda and Vari (2009)</meta>
</meta> 
```

Specifically, the code in [classes.R lines 114-123](https://github.com/ropensci/RNeXML/blob/master/R/classes.R#L114-L123) doesn't seem to be prepared for nested meta elements, and expects (in [line 117](https://github.com/ropensci/RNeXML/blob/master/R/classes.R#L117)) the `href` attribute to be present, which explains the error if it isn't because the object is "here" in the form of a content element that consists itself of meta elements. 

CC @tjv and @KuangyiXu, who reported the initial issue.

**Comment by hlapp** [comment]
Hmm. I would have expected that the value of a `LiteralMeta` is to be treated as a literal (string or number), not as a structured object, and that the value of a `ResourceMeta` is to be treated as an object, given either by a reference to a resource, or as a nested structured meta object.

It seems that the schema backs me up on this: [nexml:LiteralMeta](http://www.nexml.org/doc/schema-1/meta/annotations/#LiteralMeta) says quite clearly that the content is a string, and [nexml:ResourceMeta](http://www.nexml.org/doc/schema-1/meta/annotations/#ResourceMeta) says clearly that `href` is optional, and that it can have a substructure of zero or more elements instantiating `Meta`.

Which examples do we have that nest meta elements within `LiteralMeta`? These should fail to validate if the validator enforces that part of the schema.

Maybe the implementation was mistakenly put into the handling of `LiteralMeta` instead of `ResourceMeta`? However, I have to say I also don't see in the [`LiteralMeta` code](https://github.com/ropensci/RNeXML/blob/master/R/classes.R#L73-L86) how that would deal with nested meta elements.

**Comment by cboettig** [comment]
sorry, yeah, I had that backwards.  

We have nested examples, e.g. https://github.com/ropensci/RNeXML/blob/master/inst/examples/treebase-record.xml, but they are ResourceMeta not LiteralMeta; just as you say.  But the nesting does always includes an href, which is interpreted as the `about` element I believe.

**Comment by hlapp** [comment]
The [spec](http://www.nexml.org/doc/schema-1/meta/annotations/#ResourceMeta) actually specifically designates these as blank nodes:
> If this element contains meta elements as children, then the object of this annotation is a "blank node".
