### ISSUE TITLE
rootEdge disposable?

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#207]
Based on what I can find, there is no place in the code (or the tests) that makes any assignment to/from `tree@rootedge`, or that uses the [`rootEdge` class](https://github.com/ropensci/RNeXML/blob/master/R/classes.R#L370-L400) in some other way. Also, I just accidentally borked the class, yet that didn't result in any test failures, further corroborating the observation that this is maybe from a former time when it was needed, but is now disposable?

I'd like to remove it if it is.

**Comment by cboettig** [comment]
I think it's just there because it exists as a complexType defined in the schema, but yeah, I don't think it was actually ever used.  Not sure if that would cause a failure on parsing a NeXML file that made use of that class?  Clearly we don't have any examples in our test suite

**Comment by hlapp** [comment]
> Not sure if that would cause a failure on parsing a NeXML file that made use of that class?

I don't how it would since there is nothing instantiating it or assigning the slot. It does mean that the the file would not fully round-tripped. But there are other examples of that (such as networks ...).

**Comment by cboettig** [comment]
very true.  in any event, this is certainly disposable so do go ahead and remove the `rootEdge` class def.
