### ISSUE TITLE
Replace taxize backend

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#224]
From unrelated failures due to taxize API (#223)

> No need to make a separate API call for every taxon in a large tree (and deal with API limits, timeouts etc).  I've been working on a project with Scott and others that caches a local name database and just does the look-ups as table joins, https://github.com/cboettig/taxald, though it's not quite ready for onboarding and CRAN yet.  This'll motivate me to swap out the taxize method for this database.  (Tangential but would love your input on some of the possible strategies in taxald at some point; currently, contrary to the name, it just creates a local SQL database in MonetDBLite, or can query in a in-memory cache for setup-free use.  But am also exploring how best to turn each of the database dumps into RDF triples instead...)

**Comment by hlapp** [comment]
Completed as part of #226.
