### ISSUE TITLE
Print summary doesn't deal properly with zero phylogenetic trees

### ISSUE THREAD

**Issue by hlapp** [ropensci/RNeXML#233]
```R
> nexmls <- rphenoscape::pk_get_study_xml('https://scholar.google.com/scholar?q=The+Phylogeny+of+Ictalurid+Catfishes%3A+A+Synthesis+of+Recent+Work&btnG=&hl=en&as_sdt=0%2C42')
> nexmls[[1]]
A nexml object representing:
 	 0 phylogenetic tree blocks, where: 
 	 block 1 contains NULL phylogenetic trees
	 block 0 contains  phylogenetic trees 
 	 395 meta elements 
 	 1 character matrices 
 	 22 taxonomic units 
 Taxa: 	 Pylodictis olivaris, Ictalurus dugesii, Ameiurus platycephalus, Ameiurus catus, Ictalurus punctatus, Ameiurus natalis ... 

 NeXML generated by RNeXML using schema version: 0.9 
 size: 6.6 Mb 
```

For block 1 it incorrectly says `NULL` and for block 0 it says ` ` (whitespace?).

**Comment by cboettig** [comment]
Yup, looks like it assumes trees exist

https://github.com/ropensci/RNeXML/blob/91a6e2d6c404fd40b472140476faf8b3a75f3ad2/R/nexml_methods.R#L23-L26

Also not sure what's up with serializing the file and counting some of these using XPATH, that's probably making the method much slower than it should be.  I'd be totally on board with a rewrite of the summary method, my the current implementation looks pretty silly to me now.
