### ISSUE TITLE
tests fail with new dplyr

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#249]
@hlapp can you take a look at this as I think you're more familiar with these particular tests?

```
     Loading required package: RNeXML
     Loading required package: ape
     -- 1. Failure: coalesce_() works correctly (@test_01_utils.R#129) -------------
     `dplyr::coalesce(dta$col1, dta$col3, last)` did not throw an error.
    
     -- 2. Failure: coalesce_() works correctly (@test_01_utils.R#130) -------------
     `dplyr::coalesce(dta$col3, last)` did not throw an error.
```

**Comment by cboettig** [comment]
> Dear maintainer,

> Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_RNeXML.html>.

> Please correct before 2020-06-15 to safely retain your package on CRAN.

**Comment by hlapp** [comment]
Isn't this either fixed or obsolete?

**Comment by cboettig** [comment]
yup  fixed.
