### ISSUE TITLE
nexml.org is down, causing tests to fail

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#257]
Dear maintainer,

Please see the problems shown on
<https://cran.r-project.org/web/checks/check_results_RNeXML.html>.

Please correct before 2023-01-09 to safely retain your package on CRAN.

It seems we need to remind you of the CRAN policy:

'Packages which use Internet resources should fail gracefully with an informative message
if the resource is not available or has changed (and not give a check warning nor error).'

This needs correction whether or not the resource recovers.

The CRAN Team

**Comment by cboettig** [comment]
In the immediate term, we could run these tests conditionally on nexml.org being reachable or simply `skip_on_cran()` ?

More general question though about whether we want to continue to use the online nexml validator here though too...

**Comment by hlapp** [comment]
Yes, good question. @rvosa is the nexml.org server lost?

**Comment by rvosa** [comment]
It shouldn't be. The registration hasn't lapsed or anything. I'm
investigating.

**Comment by cboettig** [comment]
iirc I think the R function hits the online validator to perform a few additional validation steps that were not defined by the schema?

**Comment by cboettig** [comment]
@rvosa I see the schema at https://github.com/nexml/nexml/blob/master/xsd/nexml.xsd but don't seem to be able to resolve it directly from nexml.github.io/2009/nexml.xsd or similar permutations.  I think the validator will need to be able to locate the xsd includes.  

I can probably package the whole xsd directly with the R package so we can at least do offline XSD validation...

**Comment by rvosa** [comment]
Sorry, picking this up again: I think the underlying issue is the migration of our private cloud infra at Naturalis taking the validator offline. Still investigating. Apologies for the mess.

**Comment by cboettig** [comment]
no worries, we should have been falling back to offline schema-validation anyway.  I pushed a fix in 2.4.11 to CRAN so we can probably close this out here.

**Comment by hlapp** [comment]
> I pushed a fix in 2.4.11 to CRAN so we can probably close this out here.

Thanks @cboettig for doing that. (It'd be useful if next time you put changes in a PR; that way everyone gets notified who wants to be.)

In checking out the respective commits, I notice that you added a lot of `skip_on_cran()`s in places that don't obviously appear to include schema validation (and even if they did, with your change these would be offline). I assume there was a rationale behind that?

**Comment by cboettig** [comment]
:100: , apologies, I kinda rushed this one out the door to avoid getting kicked off CRAN and was thus more sloppy about my workflow.

`skip_on_cran()` was heavy-handed, but CRAN's expectations for tests that touch remote resources are draconian (see above): such a test must _never_ fail ("fail gracefully" -- i.e. fail silently without throwing a warning or an error to the check log).  Packages which are notified repeatedly for so much as throwing a warning because some internet resource didn't respond in time are accused of intentional disregard of CRAN and may be removed or blacklisted, or even the maintainer may be blacklisted for across all packages.  And sufficient defensive testing is hard given the many ways a network connection can fail -- i.e. even a successful ping to the resource once doesn't mean it won't time out on repeated calls.  

Given CRAN's interpretation of "fail gracefully" and the potentially far-reaching consequences, I think `skip_on_cran()` is a convenient approximation of tests that could touch network resources, especially as we already had our first strike above.

**Comment by hlapp** [comment]
Thanks for clarifying. I agree that the consequence of this policy has to be to be ultraconservative on which tests to allow to run. I guess it also provides a good deal of ammunition as to why packages such as Rphenoscape should perhaps never be a candidate for submission to CRAN.

The downside is that potential problems of the code with future R releases, or with interacting R packages (such as we had recently), are then much less likely to be caught at an early stage.

**Comment by cboettig** [comment]
these tests will still run on github actions.  We could also add a cron trigger to the actions here so that they are run periodically here.  

I do appreciate what CRAN does, and agree we gain by the fact that the full catalog is tested nightly on their platform (and while it's annoying to have to revise compiled code the moment a new relase of clang adds a new warning, or Apple's recent warning on any use of `sprintf` instead of `snprintf`, I'm sure we all benefit overall from these checks).   But the policy regarding internet resources and the generally high stakes associated with even occasional errors in the test suite are unfortunate, and I think a legacy of the needlessly manual workflow employed in handling occasional test suite failures at CRAN.

**Comment by rvosa** [comment]
This thread is starting to sound as if I won't be shot at dawn if the online validator stays, well, offline?

**Comment by hlapp** [comment]
Gee, I didn't know the Dutch have real rough practices when their IT goes south 😉

**Comment by rvosa** [comment]
As you know, Naturalis is basically a hospice for community websites
