### ISSUE TITLE
phyloxml support?

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#55]
@rvosa @hlapp Is there some Perl or something we could wrap to convert phyloxml into nexml, such that R users could read in that format as well?

**Comment by FabianRoger** [comment]
hej,

I was just wondering how far you have gotten with your support for phyloxml? trying to read a phyloxml tree with ```read.nexml``` I get the error message 
     
    invalid class “MethodWithNext” object: invalid object for slot "nextMethod" in class "MethodWithNext": got class "NULL", should be or extend class "PossibleMethod"

Strangely, after converting the tree to nexml with python 

    from Bio import Phylo
    Phylo.convert('example.xml', 'phyloxml', 'example2.nexml', 'nexml')

I still get the same error message. I can successfully open the phyloxml tree with Archaeopteryx though. 

thanks!

**Comment by hlapp** [comment]
@FabianRoger I do think PhyloXML support is beyond the scope of this package. Maybe you want to ask at naturalis/biovel-nbc#1?

I'd vote we close this issue as out of scope.

**Comment by gvegayon** [comment]
Hi, I just wanted to comment that I've just started a new R package to Read/Write phyloXML https://uscbiostats.github.io/rphyloxml/ (which the R-sig-phylo mail list discusses in [this thread](https://www.mail-archive.com/r-sig-phylo@r-project.org/msg05126.html)). As I already mention to @hlapp, I'm happy to think about ways to make `rphyloxml` and `RNeXML` to kind of talk to each other (either including the former as part of `RNeXML`, or attaching to dev standards used in this project).

**Comment by hlapp** [comment]
@gvegayon I'd suggest you turn this into it's own issue. I think there are two main questions here, which would benefit from having their own thread:

1. What would it take, or what should it mean to be API signature-compatible with the RNeXML package. I.e., clearly not every function/method signature would need to (or even could) be the same, but are there core functions users would use to obtain data for downstream use (such as APE matrices or tree objects for downstream comparative analysis) that could be the same for both RNeXML and rphyloXML.
2. Probably somewhat dependent on the answer to the above, how much sense does it make to have phyloXML support directly within this (the RNeXML) package, or as a separate one. I.e., how much scope creep would having it as part of RNeXML introduce, versus how much code redundancy would separate packages cause.

I don't think I have good answers to either of those, but creating a separate tracker item would give room for debate if there are people with an opinion.

**Comment by cboettig** [comment]
closing in favor of #165
