### ISSUE TITLE
Manuscript comments?

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#58]
Hi @rvosa @sckott @hlapp 

On the devel branch of the [inst/doc/pubs](https://github.com/ropensci/RNeXML/tree/master/inst/doc/pubs) directory you'll find the current draft of the [manuscript.Rmd](https://github.com/ropensci/RNeXML/blob/master/inst/doc/pubs/manuscript.Rmd) describing our RNeXML package.  I have in mind the format of a Methods in Ecology and Evolution applications note, though it may be too long for that and I'm more than open to other suggestions.  

While the draft is far from finished, I wouldn't mind getting some big-picture feedback at this stage.  Feel free to add inline comments either as text or html comments, and/or open issues with a tag for "manuscript".  

The manuscript is written in R-markdown, allowing us to embed the R code into the document so that it is run and its results displayed when compiled.  This works similarly to the README.Rmd you will see in the same directory, which is compiled to provide both the README for the github page and a pdf for the package vignette, both of which are generated using the Makefile (though the vignette will also be built during package install by default).  The manuscript can likewise be built as a markdown file or as a pdf using `make manuscript.pdf` or `make manuscript.md`, the former requiring pandoc in addition to the R libraries.  

I haven't tested all the examples yet, but mostly looking for feedback on what examples to include or move to an appendix, the overall organization/ordering of examples.  I think we need a lot more text explaining background/context too, which I'll get to soon but feel free to add since you all may do a better job framing that anyway.  

P.S. Note that we also now have continuous integration via Travis set up for the repo, so that all commits are tested against our unit test suite and R's built in checks (such that things like undocumented function arguments will also constitute a failing build).  

Cheers,

Carl

**Comment by hlapp** [comment]
@cboettig looks like we're done with this issue for now. Close?

**Comment by cboettig** [comment]
Yup, done here
