### ISSUE TITLE
write about the XML format in introduction

### ISSUE THREAD

**Issue by fmichonneau** [ropensci/RNeXML#79]
Original comment:

I think the manuscript will benefit from having a quick paragraph about some details of the XML file format. The manuscript does a good job at emphasizing that XML is well suited to store data/metadata associated with phylogenetic studies, but the manuscript lacks a section on how a XML file is organized and the definitions of some concepts that are used in the manuscript. For instance, in the section "Custom metadata extensions", the second paragraph reads:

    "We see the title appears as the value of the content attribute of this meta element."

half of the words in this sentence are mentioned for the first time here (or have been used but not defined), and it is also the first time in the manuscript that the actual content of an XML file is shown. I realize that one of the advantages of this package is to not have to deal with XML files per se, but providing, in the introduction, a brief overview of the XML format and a definition of some of the concepts of the terms used would clarify the manuscript.

**Comment by hlapp** [comment]
I'm going to make the call that this is addressed, in part with PR #106.
