### ISSUE TITLE
Advanced vignettes 

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#93]
Various topics covered in the manuscript but not in the basic README / vignette could be added as advanced vignettes.  These include:

- Adding additional metadata
- Simmap extension
- SPARQL queries
- ....

**Comment by hlapp** [comment]
I think this is addressed through the following commits:
- f20f13e2544a605f381dc49e503ef1075401d713
- 7bad1ab0d30cd7359aa04467f3f4f7d3378b65d7
- 133fa15d67a982cdbd118952d4702ac0e37eb23f
- 836da45b9293780645cae87cd6e52dba55647385
- 7b81b3a10804946eaaece6fcf2f4e37339902c08
- 7cb0ffc7d8e7323db6c34894c15e7f76c09cef3a
Ready to close out this issue?

**Comment by cboettig** [comment]
yup, thanks for tagging the commits. (I shoulda been better about tagging the relevant issue in my commit logs).
