### ISSUE TITLE
Manuscript next steps

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#95]
Hi team,

Good chat this morning. 

I merged @hlapp 's edits into `devel`, fixed the easy things, and added a few comments in reply to his comments.  I also removed old comment threads that have since been resolved.

I understand @hlapp is going to go through the manuscript to highlight:

- areas where a design decision deserves (further) discussion
- areas where we are too much in 'user manual' mode rather than merely illustrating a key conceptual use case.  
- and will also make edits / add discussion wherever appropriate.  

Feel free to push changes to your branch or `devel` so we can review them before next week's call.  

- Carl

**Comment by hlapp** [comment]
I think this is done, in part through PRs #106, #109, and #110.
