### ISSUE TITLE
Review edits on semantics, etc?

### ISSUE THREAD

**Issue by cboettig** [ropensci/RNeXML#99]
Hi @hlapp,

Wondering if you could take one more quick read over the sections I edited in response to today's call?

-  I've revised the introduction entirely, but in particular have tried to emphasize the semantic uses while still being brief (e.g. paragraph 3).  Let me know if you think we should expand that further.  

-  I've added a "future directions" section mentioning NexSON (but needs citation?) and the big files issue, though I'm not sure that my discussion is all that meaningful or if it fits in here.  (We also already point people to the rather populated [issues tracker](https://github.com/ropensci/RNeXML/milestones/Long%20term%20objectives) for future directions)

-  I've removed the part about treebase and tried to address the NEXUS parsing issue directly in the intro (para 2).  

I have to see where we stand on page limits, but might drop the 'future directions' and the 'map paragraph' from the intro to keep things shorter.  

Thanks!

**Comment by hlapp** [comment]
Done, see #106 and #109.
